info:
  Description: G'day from Config Server via GitHub. This is the SpringConfigServer application.yml
  Version: Rush.1001001.SOS
  EULA: Do whatever you want as long as you don't do anything.
  Copyright: 1984
